# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realback_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='speed',
            new_name='pace',
        ),
        migrations.AddField(
            model_name='lecture',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
