# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realback_api', '0001_squashed_0003_lecture_speed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='votes',
        ),
    ]
