# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realback_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='rating_active',
            field=models.BooleanField(default=False),
        ),
    ]
