# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realback_api', '0002_auto_20170308_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='speed',
            field=models.IntegerField(default=0),
        ),
    ]
