# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realback_api', '0002_auto_20170330_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='rating_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='rating',
            field=models.FloatField(default=1.0),
        ),
    ]
