# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realback_api', '0002_auto_20170330_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='active_topic_index',
            field=models.IntegerField(default=0),
        ),
    ]
