# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realback_api', '0003_auto_20170321_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='attendee_counter',
            field=models.IntegerField(default=0),
        ),
    ]
