# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realback_api', '0002_auto_20170314_2055'),
        ('realback_api', '0003_question_votes'),
    ]

    operations = [
    ]
