# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realback_api', '0003_auto_20170321_1830'),
        ('realback_api', '0004_merge_20170315_1101'),
    ]

    operations = [
    ]
