# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realback_api', '0004_lecture_attendee_counter'),
        ('realback_api', '0005_merge_20170322_1204'),
    ]

    operations = [
    ]
