# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realback_api', '0006_auto_20170323_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='timer_active',
            field=models.BooleanField(default=False),
        ),
    ]
