# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realback_api', '0006_merge_20170322_1422'),
        ('realback_api', '0005_lecture_lecture_activity'),
    ]

    operations = [
    ]
