# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('realback_api', '0006_auto_20170323_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lecture',
            name='timer_active',
            field=models.BooleanField(default=False),
        ),
    ]
