# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realback_api', '0006_auto_20170323_1417'),
        ('realback_api', '0008_auto_20170323_1328'),
    ]

    operations = [
    ]
