# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realback_api', '0009_merge_20170324_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='pace',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='volume',
        ),
        migrations.AddField(
            model_name='lecture',
            name='pacedown',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='paceup',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='volumedown',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='volumeup',
            field=models.IntegerField(default=0),
        ),
    ]
