# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailauth', '0002_auto_20170308_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='username', max_length=150, verbose_name='username'),
        ),
    ]
