# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='description',
        ),
    ]
